env:
    TG_BOT_TOKEN: "ENCRYPTED[]"
    CHATID: "ENCRYPTED[]"
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/home"
task:
    name: Android Kernel Build
    timeout_in: 120m # max 120m
    container:
      image: 54b1d/kernel_build:latest
      cpu: 8 # max 8
      memory: 32G # max 32G
    build_script:
      - chmod +x *
      - ./build tortoise  # ./build branch_name nolto
